server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
              
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: drunker-service
        uri: lb://drunker-service
        predicates:
        - Path=/employee/**
        filters:
        - RewritePath=/drunker/(?<path>.*), /$\{path}
      - id: department-service
        uri: lb://drunker-filestorage-service
        predicates:
        - Path=/drunker-filestorage/**
        filters:
        - RewritePath=/drunker-filestorage/(?<path>.*), /$\{path}
      - id: openapi
        uri: http://localhost:${server.port}
        predicates:
        - Path=/v3/api-docs/**
        filters:
        - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs